<?xml version="1.0"?>
<robot name="diff_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find diff_drive_description)/models/base.xacro" />
    <xacro:include filename="$(find diff_drive_description)/models/sensors/laser.xacro" />
    <xacro:include filename="$(find diff_drive_description)/models/sensors/camera.xacro" />

    <xacro:property name="laser_offset_x" value="0" />
    <xacro:property name="laser_offset_y" value="0" />
    <xacro:property name="laser_offset_z" value="${2*caster_radius + base_length + laser_length/2}" />

    <xacro:property name="camera_offset_x" value="0.18" />
    <xacro:property name="camera_offset_y" value="0" />
    <xacro:property name="camera_offset_z" value="0.165" />

    <!-- 调用base宏 -->
    <xacro:diff_drive_base />

    <!-- laser_joint -->
    <joint name="laser_joint" type="fixed">
        <origin xyz="${laser_offset_x} ${laser_offset_y} ${laser_offset_z}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="laser_link" />
    </joint>

    <!-- 调用laser宏 -->
    <xacro:laser prefix="laser" />

    <!-- camera_joint -->
    <joint name="camera_joint" type="fixed">
        <origin xyz="${camera_offset_x} ${camera_offset_y} ${camera_offset_z}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="camera_link" />
    </joint>

    <!-- 调用Camera宏 -->
    <xacro:usb_camera prefix="camera" />

</robot>